services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d colegio" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: martromeros/api-gateway:latest
    container_name: nginx
    restart: always
    depends_on:
      - ms-auth
      - ms-asistencia
      - ms-comunicaciones
      - ms-gestion
    ports:
      - "80:80"

  ms-auth:
    image: martromeros/ms-auth:latest
    container_name: ms_auth
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      JWT_SECRET: ${JWT_SECRET}
      SALT_ROUNDS: ${SALT_ROUNDS}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}

  ms-asistencia:
    image: martromeros/ms-asistencia:latest
    container_name: ms_asistencia
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      PORT: "3001"
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}

  ms-comunicaciones:
    image: martromeros/ms-comunicaciones:latest
    container_name: ms_comunicaciones
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
    ports:
      - "3002:3002"
    environment:
      PORT: "3002"
      UPLOAD_PATH: ${UPLOAD_PATH}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      RABBITMQ_URL: amqp://admin:admin123@rabbit-mq:5672
      

  ms-gestion:
    image: martromeros/ms-gestion:latest
    container_name: ms_gestion
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbit-mq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
  ms-matricula:
    image: martromeros/ms-matricula:latest
    container_name: ms_matricula
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:3003"
    environment:
      DB_URL: postgresql://postgres:secure-key@db:5432/colegio
      #WEBPAY_COMMERCE_CODE: ${WEBPAY_COMMERCE_CODE}
      #WEBPAY_API_KEY: ${WEBPAY_API_KEY}
      


  rabbit-mq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
