CREATE TABLE "roles" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "usuarios" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol_id" integer,
  "rut" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido_paterno" varchar NOT NULL,
  "apellido_materno" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar  NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "estudiantes" (
  "estudiante_id" integer PRIMARY KEY,
  "curso_id" integer
);

CREATE TABLE "docentes" (
  "docente_id" integer PRIMARY KEY,
  "especialidad" varchar
);

CREATE TABLE "apoderados" (
  "apoderado_id" integer PRIMARY KEY
);

CREATE TABLE "apoderado_estudiante" (
  "apoderado_id" integer,
  "estudiante_id" integer,
  PRIMARY KEY ("apoderado_id", "estudiante_id")
);

CREATE TABLE "asignaturas" (
  "asignatura_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "siglas" varchar UNIQUE
);

CREATE TABLE "cursos" (
  "curso_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" varchar NOT NULL,
  "letra" char(1) NOT NULL,
  "anio_academico" integer NOT NULL
);

CREATE TABLE "curso_asignatura_docente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" integer,
  "asignatura_id" integer,
  "docente_id" integer
);

CREATE TABLE "evaluaciones" (
  "evaluacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cad_id" integer,
  "nombre" varchar NOT NULL,
  "fecha_evaluacion" date
);

CREATE TABLE "notas" (
  "nota_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evaluacion_id" integer,
  "estudiante_id" integer,
  "valor" float NOT NULL
);

CREATE TABLE "asistencia" (
  "asistencia_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" integer,
  "cad_id" integer,
  "fecha" date NOT NULL,
  "estado" varchar NOT NULL,
  "tipo_asistencia" varchar
);

CREATE TABLE "anotaciones" (
  "anotacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" integer,
  "docente_id" integer,
  "tipo" varchar NOT NULL,
  "descripcion" text NOT NULL,
  "fecha_registro" timestamp DEFAULT (now())
);

CREATE TABLE "salas" (
  "sala_id" serial PRIMARY KEY
);

CREATE TABLE "sala_evaluacione_asistencia" (
  "sala_id" integer,
  "evaluacion_id" integer,
  "asistencia_id" integer
);

ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("rol_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estudiantes" ADD FOREIGN KEY ("estudiante_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estudiantes" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("curso_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "docentes" ADD FOREIGN KEY ("docente_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoderados" ADD FOREIGN KEY ("apoderado_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoderado_estudiante" ADD FOREIGN KEY ("apoderado_id") REFERENCES "apoderados" ("apoderado_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoderado_estudiante" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("curso_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("asignatura_id") REFERENCES "asignaturas" ("asignatura_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("docente_id") REFERENCES "docentes" ("docente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluaciones" ADD FOREIGN KEY ("cad_id") REFERENCES "curso_asignatura_docente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notas" ADD FOREIGN KEY ("evaluacion_id") REFERENCES "evaluaciones" ("evaluacion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notas" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("cad_id") REFERENCES "curso_asignatura_docente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anotaciones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anotaciones" ADD FOREIGN KEY ("docente_id") REFERENCES "docentes" ("docente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_evaluacione_asistencia" ADD FOREIGN KEY ("sala_id") REFERENCES "salas" ("sala_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_evaluacione_asistencia" ADD FOREIGN KEY ("evaluacion_id") REFERENCES "evaluaciones" ("evaluacion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_evaluacione_asistencia" ADD FOREIGN KEY ("asistencia_id") REFERENCES "asistencia" ("asistencia_id") DEFERRABLE INITIALLY IMMEDIATE;


-- 1. Limpiar datos previos
TRUNCATE roles, usuarios, estudiantes, docentes, apoderados, cursos, asignaturas, curso_asignatura_docente, evaluaciones, notas, asistencia, anotaciones, salas, sala_evaluacione_asistencia CASCADE;

-- 2. Insertar Roles
INSERT INTO roles (rol_id, nombre) VALUES
(1, 'Administrador'),
(2, 'Docente'),
(3, 'Estudiante');

-- 3. Insertar Usuarios Administrativos y Docentes base
INSERT INTO usuarios (usuario_id, rol_id, rut, nombre, apellido_paterno, apellido_materno, email, password) VALUES
(1, 1, '11.111.111-1', 'Admin', 'Sistema', 'Principal', 'admin@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(2, 2, '12.222.222-2', 'Carla', 'Rodríguez', 'Pérez', 'c.rodriguez@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(3, 2, '13.333.333-3', 'Marcos', 'Soto', 'López', 'm.soto@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- Tres nuevos docentes
(4, 2, '14.444.444-4', 'Patricia', 'Rojas', 'Díaz', 'p.rojas@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(5, 2, '15.555.555-5', 'Andrés', 'Castro', 'Silva', 'a.castro@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(6, 2, '16.666.666-6', 'Elena', 'Morales', 'Ramos', 'e.morales@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y');

-- Especialidad principal de cada docente (referencia informativa; la asignación real es en curso_asignatura_docente)
INSERT INTO docentes (docente_id, especialidad) VALUES
(2, 'Matemáticas y Física'),
(3, 'Lenguaje y Comunicación'),
(4, 'Historia y Geografía'),
(5, 'Ciencias Naturales'),
(6, 'Inglés y Artes');

-- 4. Inserción de Cursos: desde 1° Básico hasta 4° Medio, letras A y B
INSERT INTO cursos (nivel, letra, anio_academico) VALUES
('1° Básico',  'A', 2024),
('1° Básico',  'B', 2024),
('2° Básico',  'A', 2024),
('2° Básico',  'B', 2024),
('3° Básico',  'A', 2024),
('3° Básico',  'B', 2024),
('4° Básico',  'A', 2024),
('4° Básico',  'B', 2024),
('5° Básico',  'A', 2024),
('5° Básico',  'B', 2024),
('6° Básico',  'A', 2024),
('6° Básico',  'B', 2024),
('7° Básico',  'A', 2024),
('7° Básico',  'B', 2024),
('8° Básico',  'A', 2024),
('8° Básico',  'B', 2024),
('1° Medio',   'A', 2024),
('1° Medio',   'B', 2024),
('2° Medio',   'A', 2024),
('2° Medio',   'B', 2024),
('3° Medio',   'A', 2024),
('3° Medio',   'B', 2024),
('4° Medio',   'A', 2024),
('4° Medio',   'B', 2024);

-- 5. Generación de Salas (una por curso: 24 salas)
INSERT INTO salas (sala_id)
SELECT generate_series(1, (SELECT count(*) FROM cursos));

-- 6. Insertar Estudiantes (solo en cursos con docente asignado, máximo 10 por curso)
-- Cursos activos: 1°B-A (ID 1), 1°B-B (ID 2), 2°B-A (ID 3), 1°M-A (ID 17), 2°M-A (ID 19)
-- IDs de usuario: 100-149 (sin conflicto con admin/docentes 1-6)
INSERT INTO usuarios (usuario_id, rol_id, rut, nombre, apellido_paterno, apellido_materno, email, password) VALUES
-- 1° Básico A (10 alumnos, IDs 100-109)
(100, 3, '20.100.001-5', 'Sofía',     'González',  'Muñoz',     'sofia.gonzalez@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(101, 3, '20.100.002-6', 'Diego',     'Ramírez',   'Torres',    'diego.ramirez@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(102, 3, '20.100.003-7', 'Valentina', 'Flores',    'Herrera',   'valentina.flores@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(103, 3, '20.100.004-8', 'Matías',    'Morales',   'Vega',      'matias.morales@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(104, 3, '20.100.005-9', 'Isabella',  'Castro',    'Pino',      'isabella.castro@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(105, 3, '20.100.006-0', 'Lucas',     'Jiménez',   'Ríos',      'lucas.jimenez@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(106, 3, '20.100.007-1', 'Antonia',   'Vargas',    'Salinas',   'antonia.vargas@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(107, 3, '20.100.008-2', 'Benjamín',  'Soto',      'Espinoza',  'benjamin.soto@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(108, 3, '20.100.009-3', 'Camila',    'Reyes',     'Fuentes',   'camila.reyes@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(109, 3, '20.100.010-4', 'Sebastián', 'Rojas',     'Mena',      'sebastian.rojas@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 1° Básico B (10 alumnos, IDs 110-119)
(110, 3, '20.110.001-6', 'Fernanda',  'Pérez',     'Lagos',     'fernanda.perez@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(111, 3, '20.110.002-7', 'Nicolás',   'Álvarez',   'Contreras', 'nicolas.alvarez@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(112, 3, '20.110.003-8', 'Emilia',    'Torres',    'Navarro',   'emilia.torres@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(113, 3, '20.110.004-9', 'Tomás',     'Díaz',      'Guerrero',  'tomas.diaz@colegio.cl',       '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(114, 3, '20.110.005-0', 'Catalina',  'Ortega',    'Miranda',   'catalina.ortega@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(115, 3, '20.110.006-1', 'Agustín',   'Gutiérrez', 'Campos',    'agustin.gutierrez@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(116, 3, '20.110.007-2', 'Isidora',   'Núñez',     'Vera',      'isidora.nunez@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(117, 3, '20.110.008-3', 'Felipe',    'Medina',    'Araya',     'felipe.medina@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(118, 3, '20.110.009-4', 'Renata',    'Molina',    'Cáceres',   'renata.molina@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(119, 3, '20.110.010-5', 'Joaquín',   'Silva',     'Bravo',     'joaquin.silva@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 2° Básico A (10 alumnos, IDs 120-129)
(120, 3, '20.120.001-7', 'Amaranta',  'Fuentes',   'Ibáñez',    'amaranta.fuentes@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(121, 3, '20.120.002-8', 'Rodrigo',   'Herrera',   'Pinto',     'rodrigo.herrera@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(122, 3, '20.120.003-9', 'Violeta',   'Lara',      'Sepúlveda', 'violeta.lara@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(123, 3, '20.120.004-0', 'Cristóbal', 'Vega',      'Sandoval',  'cristobal.vega@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(124, 3, '20.120.005-1', 'Javiera',   'Arce',      'Cid',       'javiera.arce@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(125, 3, '20.120.006-2', 'Ignacio',   'Contreras', 'Leiva',     'ignacio.contreras@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(126, 3, '20.120.007-3', 'Francisca', 'Espinoza',  'Ojeda',     'francisca.espinoza@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(127, 3, '20.120.008-4', 'Maximiliano','Castillo',  'Opazo',     'maximiliano.castillo@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(128, 3, '20.120.009-5', 'Trinidad',  'Sánchez',   'Muñoz',     'trinidad.sanchez@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(129, 3, '20.120.010-6', 'Vicente',   'Valenzuela','Carreño',   'vicente.valenzuela@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 1° Medio A (10 alumnos, IDs 130-139)
(130, 3, '20.130.001-8', 'Gabriela',  'Paredes',   'Riquelme',  'gabriela.paredes@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(131, 3, '20.130.002-9', 'Alonso',    'Tapia',     'Aguilar',   'alonso.tapia@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(132, 3, '20.130.003-0', 'Martina',   'Reyes',     'Donoso',    'martina.reyes@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(133, 3, '20.130.004-1', 'Gonzalo',   'Muñoz',     'Acuña',     'gonzalo.munoz@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(134, 3, '20.130.005-2', 'Pilar',     'Bravo',     'Figueroa',  'pilar.bravo@colegio.cl',      '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(135, 3, '20.130.006-3', 'Óscar',     'Cortés',    'Lobos',     'oscar.cortes@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(136, 3, '20.130.007-4', 'Renée',     'Poblete',   'Farías',    'renee.poblete@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(137, 3, '20.130.008-5', 'Andrés',    'Olivares',  'Henríquez', 'andres.olivares@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(138, 3, '20.130.009-6', 'Paula',     'Vallejos',  'Carrasco',  'paula.vallejos@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(139, 3, '20.130.010-7', 'Esteban',   'Meza',      'Bustamante','esteban.meza@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 2° Medio A (10 alumnos, IDs 140-149)
(140, 3, '20.140.001-9', 'Rocío',     'Vidal',     'Espejo',    'rocio.vidal@colegio.cl',      '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(141, 3, '20.140.002-0', 'Patricio',  'Cerda',     'Rojas',     'patricio.cerda@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(142, 3, '20.140.003-1', 'Andrea',    'Lagos',     'Sepúlveda', 'andrea.lagos@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(143, 3, '20.140.004-2', 'Roberto',   'Arriagada', 'Díaz',      'roberto.arriagada@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(144, 3, '20.140.005-3', 'Constanza', 'Ibarra',    'Pizarro',   'constanza.ibarra@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(145, 3, '20.140.006-4', 'Simón',     'Cárdenas',  'Cuevas',    'simon.cardenas@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(146, 3, '20.140.007-5', 'Loreto',    'Garrido',   'Villalobos','loreto.garrido@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(147, 3, '20.140.008-6', 'Cristián',  'Henríquez', 'Troncoso',  'cristian.henriquez@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(148, 3, '20.140.009-7', 'Daniela',   'Riffo',     'Zuñiga',    'daniela.riffo@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(149, 3, '20.140.010-8', 'Manuel',    'Espinoza',  'Vergara',   'manuel.espinoza@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y');

-- Vincular estudiantes a sus cursos
INSERT INTO estudiantes (estudiante_id, curso_id) VALUES
-- 1° Básico A (curso_id = 1)
(100, 1), (101, 1), (102, 1), (103, 1), (104, 1),
(105, 1), (106, 1), (107, 1), (108, 1), (109, 1),
-- 1° Básico B (curso_id = 2)
(110, 2), (111, 2), (112, 2), (113, 2), (114, 2),
(115, 2), (116, 2), (117, 2), (118, 2), (119, 2),
-- 2° Básico A (curso_id = 3)
(120, 3), (121, 3), (122, 3), (123, 3), (124, 3),
(125, 3), (126, 3), (127, 3), (128, 3), (129, 3),
-- 1° Medio A (curso_id = 17)
(130, 17), (131, 17), (132, 17), (133, 17), (134, 17),
(135, 17), (136, 17), (137, 17), (138, 17), (139, 17),
-- 2° Medio A (curso_id = 19)
(140, 19), (141, 19), (142, 19), (143, 19), (144, 19),
(145, 19), (146, 19), (147, 19), (148, 19), (149, 19);

-- 7. Insertar Asignaturas Base
INSERT INTO asignaturas (nombre, siglas) VALUES
('Matemática', 'MAT01'),
('Lenguaje', 'LEN01'),
('Historia', 'HIS01'),
('Ciencias Naturales', 'CIE01'),
('Inglés', 'ING01'),
('Artes Visuales', 'ART01'),
('Educación Física', 'EDF01');

-- 8. Relaciones académicas: curso_asignatura_docente permite que un docente imparta
-- múltiples asignaturas en distintos cursos (sin restricción UNIQUE sobre docente_id).
INSERT INTO curso_asignatura_docente (curso_id, asignatura_id, docente_id) VALUES
-- Carla (ID 2): Matemática en 1° Básico A y B (cursos 1 y 2)
(1, 1, 2),
(2, 1, 2),
-- Marcos (ID 3): Lenguaje en 1° Básico A y 2° Básico A (cursos 1 y 3)
(1, 2, 3),
(3, 2, 3),
-- Patricia (ID 4): Historia en 1° Básico A y 2° Básico A (cursos 1 y 3)
(1, 3, 4),
(3, 3, 4),
-- Andrés (ID 5): Ciencias en 2° Básico A y Educación Física en 1° Básico A (cursos 3 y 1)
(3, 4, 5),
(1, 7, 5),
-- Elena (ID 6): Inglés en 1° Medio A y Artes en 2° Medio A (cursos 17 y 19)
(17, 5, 6),
(19, 6, 6);

