CREATE TABLE "roles" (
  "rol_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "usuarios" (
  "usuario_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol_id" integer,
  "rut" varchar UNIQUE NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido_paterno" varchar NOT NULL,
  "apellido_materno" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar  NOT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "estudiantes" (
  "estudiante_id" integer PRIMARY KEY,
  "curso_id" integer
);

CREATE TABLE "docentes" (
  "docente_id" integer PRIMARY KEY,
  "especialidad" varchar
);

CREATE TABLE "apoderados" (
  "apoderado_id" integer PRIMARY KEY
);

CREATE TABLE "apoderado_estudiante" (
  "apoderado_id" integer,
  "estudiante_id" integer,
  PRIMARY KEY ("apoderado_id", "estudiante_id")
);

CREATE TABLE "asignaturas" (
  "asignatura_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar NOT NULL,
  "siglas" varchar UNIQUE
);

CREATE TABLE "cursos" (
  "curso_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel" varchar NOT NULL,
  "letra" char(1) NOT NULL,
  "anio_academico" integer NOT NULL,
  "cupos" integer NOT NULL DEFAULT 20
);

CREATE TABLE "curso_asignatura_docente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "curso_id" integer,
  "asignatura_id" integer,
  "docente_id" integer,
  "sala_id" integer
);

CREATE TABLE "evaluaciones" (
  "evaluacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cad_id" integer,
  "nombre" varchar NOT NULL,
  "fecha_evaluacion" date
);

CREATE TABLE "notas" (
  "nota_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "evaluacion_id" integer,
  "estudiante_id" integer,
  "valor" float NOT NULL
);

CREATE TABLE "asistencia" (
  "asistencia_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" integer,
  "cad_id" integer,
  "fecha" date NOT NULL,
  "estado" varchar NOT NULL,
  "tipo_asistencia" varchar
);

CREATE TABLE "anotaciones" (
  "anotacion_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estudiante_id" integer,
  "docente_id" integer,
  "tipo" varchar NOT NULL,
  "descripcion" text NOT NULL,
  "fecha_registro" timestamp DEFAULT (now())
);

CREATE TABLE "salas" (
  "sala_id" serial PRIMARY KEY,
  "nombre" varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS mensajeria (
    id SERIAL PRIMARY KEY,
    quien_envia VARCHAR(150) NOT NULL,
    quien_recibe VARCHAR(150) NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    asunto VARCHAR(255) NOT NULL,
    cuerpo_mensaje TEXT,
    -- Cambiamos id_archivo_adjunto de UUID a TEXT para guardar la ruta solicitada
    id_archivo_adjunto TEXT, 
    leido BOOLEAN DEFAULT FALSE
);


ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("rol_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estudiantes" ADD FOREIGN KEY ("estudiante_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "estudiantes" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("curso_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "docentes" ADD FOREIGN KEY ("docente_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoderados" ADD FOREIGN KEY ("apoderado_id") REFERENCES "usuarios" ("usuario_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoderado_estudiante" ADD FOREIGN KEY ("apoderado_id") REFERENCES "apoderados" ("apoderado_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "apoderado_estudiante" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("curso_id") REFERENCES "cursos" ("curso_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("asignatura_id") REFERENCES "asignaturas" ("asignatura_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("docente_id") REFERENCES "docentes" ("docente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluaciones" ADD FOREIGN KEY ("cad_id") REFERENCES "curso_asignatura_docente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notas" ADD FOREIGN KEY ("evaluacion_id") REFERENCES "evaluaciones" ("evaluacion_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notas" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asistencia" ADD FOREIGN KEY ("cad_id") REFERENCES "curso_asignatura_docente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anotaciones" ADD FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes" ("estudiante_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anotaciones" ADD FOREIGN KEY ("docente_id") REFERENCES "docentes" ("docente_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "curso_asignatura_docente" ADD FOREIGN KEY ("sala_id") REFERENCES "salas" ("sala_id") DEFERRABLE INITIALLY IMMEDIATE;


-- Trigger: impide inscribir estudiante si el curso alcanzó su cupo
CREATE OR REPLACE FUNCTION verificar_cupo_curso()
RETURNS TRIGGER AS $$
DECLARE
  cupo_max integer;
  cupo_actual integer;
BEGIN
  SELECT cupos INTO cupo_max FROM cursos WHERE curso_id = NEW.curso_id;
  SELECT COUNT(*) INTO cupo_actual FROM estudiantes WHERE curso_id = NEW.curso_id;
  IF cupo_actual >= cupo_max THEN
    RAISE EXCEPTION 'El curso % ha alcanzado su cupo máximo de % estudiantes.', NEW.curso_id, cupo_max;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_verificar_cupo
BEFORE INSERT ON estudiantes
FOR EACH ROW EXECUTE FUNCTION verificar_cupo_curso();

-- 1. Limpiar datos previos
TRUNCATE roles, usuarios, estudiantes, docentes, apoderados, cursos, asignaturas, curso_asignatura_docente, evaluaciones, notas, asistencia, anotaciones, salas, mensajeria CASCADE;

-- 2. Insertar Roles
INSERT INTO roles (rol_id, nombre) VALUES
(1, 'Administrador'),
(2, 'Docente'),
(3, 'Estudiante'),
(4, 'Apoderado');

-- 3. Insertar Usuarios Administrativos y Docentes base
INSERT INTO usuarios (usuario_id, rol_id, rut, nombre, apellido_paterno, apellido_materno, email, password) VALUES
(1, 1, '11.111.111-1', 'Admin', 'Sistema', 'Principal', 'admin@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(2, 2, '12.222.222-2', 'Carla', 'Rodríguez', 'Pérez', 'c.rodriguez@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(3, 2, '13.333.333-3', 'Marcos', 'Soto', 'López', 'm.soto@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- Tres nuevos docentes
(4, 2, '14.444.444-4', 'Patricia', 'Rojas', 'Díaz', 'p.rojas@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(5, 2, '15.555.555-5', 'Andrés', 'Castro', 'Silva', 'a.castro@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(6, 2, '16.666.666-6', 'Elena', 'Morales', 'Ramos', 'e.morales@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y');

-- Especialidad principal de cada docente (referencia informativa; la asignación real es en curso_asignatura_docente)
INSERT INTO docentes (docente_id, especialidad) VALUES
(2, 'Matemáticas y Física'),
(3, 'Lenguaje y Comunicación'),
(4, 'Historia y Geografía'),
(5, 'Ciencias Naturales'),
(6, 'Inglés y Artes');

-- 4. Inserción de Cursos: desde 1° Básico hasta 4° Medio, letras A y B
-- IDs resultantes: 1°B-A=1, 1°B-B=2, 2°B-A=3, ..., 1°M-A=17, 1°M-B=18, 2°M-A=19, ..., 4°M-B=24
INSERT INTO cursos (nivel, letra, anio_academico) VALUES
('1° Básico',  'A', 2024),
('1° Básico',  'B', 2024),
('2° Básico',  'A', 2024),
('2° Básico',  'B', 2024),
('3° Básico',  'A', 2024),
('3° Básico',  'B', 2024),
('4° Básico',  'A', 2024),
('4° Básico',  'B', 2024),
('5° Básico',  'A', 2024),
('5° Básico',  'B', 2024),
('6° Básico',  'A', 2024),
('6° Básico',  'B', 2024),
('7° Básico',  'A', 2024),
('7° Básico',  'B', 2024),
('8° Básico',  'A', 2024),
('8° Básico',  'B', 2024),
('1° Medio',   'A', 2024),
('1° Medio',   'B', 2024),
('2° Medio',   'A', 2024),
('2° Medio',   'B', 2024),
('3° Medio',   'A', 2024),
('3° Medio',   'B', 2024),
('4° Medio',   'A', 2024),
('4° Medio',   'B', 2024);

-- 5. Generación de Salas (una por curso: 24 salas)
INSERT INTO salas (sala_id, nombre)
SELECT gs, 'Sala ' || gs
FROM generate_series(1, (SELECT count(*)::int FROM cursos)) AS gs;

-- 6. Insertar Estudiantes (solo en cursos con docente asignado, máximo 10 por curso)
-- Cursos activos: 1°B-A (ID 1), 1°B-B (ID 2), 2°B-A (ID 3), 1°M-A (ID 17), 2°M-A (ID 19)
-- IDs de usuario: 100-149 (sin conflicto con admin/docentes 1-6)
INSERT INTO usuarios (usuario_id, rol_id, rut, nombre, apellido_paterno, apellido_materno, email, password) VALUES
-- 1° Básico A (10 alumnos, IDs 100-109)
(100, 3, '20.100.001-5', 'Sofía',     'González',  'Muñoz',     'sofia.gonzalez@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(101, 3, '20.100.002-6', 'Diego',     'Ramírez',   'Torres',    'diego.ramirez@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(102, 3, '20.100.003-7', 'Valentina', 'Flores',    'Herrera',   'valentina.flores@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(103, 3, '20.100.004-8', 'Matías',    'Morales',   'Vega',      'matias.morales@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(104, 3, '20.100.005-9', 'Isabella',  'Castro',    'Pino',      'isabella.castro@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(105, 3, '20.100.006-0', 'Lucas',     'Jiménez',   'Ríos',      'lucas.jimenez@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(106, 3, '20.100.007-1', 'Antonia',   'Vargas',    'Salinas',   'antonia.vargas@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(107, 3, '20.100.008-2', 'Benjamín',  'Soto',      'Espinoza',  'benjamin.soto@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(108, 3, '20.100.009-3', 'Camila',    'Reyes',     'Fuentes',   'camila.reyes@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(109, 3, '20.100.010-4', 'Sebastián', 'Rojas',     'Mena',      'sebastian.rojas@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 1° Básico B (10 alumnos, IDs 110-119)
(110, 3, '20.110.001-6', 'Fernanda',  'Pérez',     'Lagos',     'fernanda.perez@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(111, 3, '20.110.002-7', 'Nicolás',   'Álvarez',   'Contreras', 'nicolas.alvarez@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(112, 3, '20.110.003-8', 'Emilia',    'Torres',    'Navarro',   'emilia.torres@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(113, 3, '20.110.004-9', 'Tomás',     'Díaz',      'Guerrero',  'tomas.diaz@colegio.cl',       '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(114, 3, '20.110.005-0', 'Catalina',  'Ortega',    'Miranda',   'catalina.ortega@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(115, 3, '20.110.006-1', 'Agustín',   'Gutiérrez', 'Campos',    'agustin.gutierrez@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(116, 3, '20.110.007-2', 'Isidora',   'Núñez',     'Vera',      'isidora.nunez@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(117, 3, '20.110.008-3', 'Felipe',    'Medina',    'Araya',     'felipe.medina@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(118, 3, '20.110.009-4', 'Renata',    'Molina',    'Cáceres',   'renata.molina@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(119, 3, '20.110.010-5', 'Joaquín',   'Silva',     'Bravo',     'joaquin.silva@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 2° Básico A (10 alumnos, IDs 120-129)
(120, 3, '20.120.001-7', 'Amaranta',  'Fuentes',   'Ibáñez',    'amaranta.fuentes@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(121, 3, '20.120.002-8', 'Rodrigo',   'Herrera',   'Pinto',     'rodrigo.herrera@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(122, 3, '20.120.003-9', 'Violeta',   'Lara',      'Sepúlveda', 'violeta.lara@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(123, 3, '20.120.004-0', 'Cristóbal', 'Vega',      'Sandoval',  'cristobal.vega@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(124, 3, '20.120.005-1', 'Javiera',   'Arce',      'Cid',       'javiera.arce@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(125, 3, '20.120.006-2', 'Ignacio',   'Contreras', 'Leiva',     'ignacio.contreras@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(126, 3, '20.120.007-3', 'Francisca', 'Espinoza',  'Ojeda',     'francisca.espinoza@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(127, 3, '20.120.008-4', 'Maximiliano','Castillo',  'Opazo',     'maximiliano.castillo@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(128, 3, '20.120.009-5', 'Trinidad',  'Sánchez',   'Muñoz',     'trinidad.sanchez@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(129, 3, '20.120.010-6', 'Vicente',   'Valenzuela','Carreño',   'vicente.valenzuela@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 1° Medio A (10 alumnos, IDs 130-139)
(130, 3, '20.130.001-8', 'Gabriela',  'Paredes',   'Riquelme',  'gabriela.paredes@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(131, 3, '20.130.002-9', 'Alonso',    'Tapia',     'Aguilar',   'alonso.tapia@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(132, 3, '20.130.003-0', 'Martina',   'Reyes',     'Donoso',    'martina.reyes@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(133, 3, '20.130.004-1', 'Gonzalo',   'Muñoz',     'Acuña',     'gonzalo.munoz@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(134, 3, '20.130.005-2', 'Pilar',     'Bravo',     'Figueroa',  'pilar.bravo@colegio.cl',      '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(135, 3, '20.130.006-3', 'Óscar',     'Cortés',    'Lobos',     'oscar.cortes@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(136, 3, '20.130.007-4', 'Renée',     'Poblete',   'Farías',    'renee.poblete@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(137, 3, '20.130.008-5', 'Andrés',    'Olivares',  'Henríquez', 'andres.olivares@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(138, 3, '20.130.009-6', 'Paula',     'Vallejos',  'Carrasco',  'paula.vallejos@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(139, 3, '20.130.010-7', 'Esteban',   'Meza',      'Bustamante','esteban.meza@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
-- 2° Medio A (10 alumnos, IDs 140-149)
(140, 3, '20.140.001-9', 'Rocío',     'Vidal',     'Espejo',    'rocio.vidal@colegio.cl',      '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(141, 3, '20.140.002-0', 'Patricio',  'Cerda',     'Rojas',     'patricio.cerda@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(142, 3, '20.140.003-1', 'Andrea',    'Lagos',     'Sepúlveda', 'andrea.lagos@colegio.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(143, 3, '20.140.004-2', 'Roberto',   'Arriagada', 'Díaz',      'roberto.arriagada@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(144, 3, '20.140.005-3', 'Constanza', 'Ibarra',    'Pizarro',   'constanza.ibarra@colegio.cl', '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(145, 3, '20.140.006-4', 'Simón',     'Cárdenas',  'Cuevas',    'simon.cardenas@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(146, 3, '20.140.007-5', 'Loreto',    'Garrido',   'Villalobos','loreto.garrido@colegio.cl',   '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(147, 3, '20.140.008-6', 'Cristián',  'Henríquez', 'Troncoso',  'cristian.henriquez@colegio.cl','$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(148, 3, '20.140.009-7', 'Daniela',   'Riffo',     'Zuñiga',    'daniela.riffo@colegio.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(149, 3, '20.140.010-8', 'Manuel',    'Espinoza',  'Vergara',   'manuel.espinoza@colegio.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y');

-- Vincular estudiantes a sus cursos
INSERT INTO estudiantes (estudiante_id, curso_id) VALUES
-- 1° Básico A (curso_id = 1)
(100, 1), (101, 1), (102, 1), (103, 1), (104, 1),
(105, 1), (106, 1), (107, 1), (108, 1), (109, 1),
-- 1° Básico B (curso_id = 2)
(110, 2), (111, 2), (112, 2), (113, 2), (114, 2),
(115, 2), (116, 2), (117, 2), (118, 2), (119, 2),
-- 2° Básico A (curso_id = 3)
(120, 3), (121, 3), (122, 3), (123, 3), (124, 3),
(125, 3), (126, 3), (127, 3), (128, 3), (129, 3),
-- 1° Medio A (curso_id = 17)
(130, 17), (131, 17), (132, 17), (133, 17), (134, 17),
(135, 17), (136, 17), (137, 17), (138, 17), (139, 17),
-- 2° Medio A (curso_id = 19)
(140, 19), (141, 19), (142, 19), (143, 19), (144, 19),
(145, 19), (146, 19), (147, 19), (148, 19), (149, 19);

-- 7. Insertar Asignaturas Base
INSERT INTO asignaturas (nombre, siglas) VALUES
('Matemática', 'MAT01'),
('Lenguaje', 'LEN01'),
('Historia', 'HIS01'),
('Ciencias Naturales', 'CIE01'),
('Inglés', 'ING01'),
('Artes Visuales', 'ART01'),
('Educación Física', 'EDF01');

-- 8. Apoderados (rol_id=4, IDs 200-204)
INSERT INTO usuarios (usuario_id, rol_id, rut, nombre, apellido_paterno, apellido_materno, email, password) VALUES
(200, 4, '30.200.001-1', 'Carmen',  'González', 'Soto',    'carmen.gonzalez@mail.cl',  '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(201, 4, '30.200.002-2', 'Jorge',   'Ramírez',  'Lagos',   'jorge.ramirez@mail.cl',    '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(202, 4, '30.200.003-3', 'Ana',     'Flores',   'Morales', 'ana.flores@mail.cl',       '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(203, 4, '30.200.004-4', 'Pedro',   'Castro',   'Reyes',   'pedro.castro@mail.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y'),
(204, 4, '30.200.005-5', 'Lucía',   'Medina',   'Vega',    'lucia.medina@mail.cl',     '$2a$12$Iy8XTvbNC7Y.RWipf8O8f.vNU3VrVNC9m4Iq.02bPi.6pRbHYL66y');

INSERT INTO apoderados (apoderado_id) VALUES (200), (201), (202), (203), (204);

-- Cada apoderado cubre estudiantes del mismo curso
INSERT INTO apoderado_estudiante (apoderado_id, estudiante_id) VALUES
(200, 100), (200, 101), (200, 102),
(201, 110), (201, 111), (201, 112),
(202, 120), (202, 121), (202, 122),
(203, 130), (203, 131), (203, 132),
(204, 140), (204, 141), (204, 142);

-- 9. Asignación Curso-Asignatura-Docente (5 asignaturas × 5 cursos activos = 25 registros)
-- Docentes: 2=Matemáticas, 3=Lenguaje, 4=Historia, 5=Ciencias Naturales, 6=Inglés
-- sala_id coincide con curso_id (una sala física por curso)
-- cad_id secuencial: 1-5 → curso 1, 6-10 → curso 2, 11-15 → curso 3, 16-20 → curso 17, 21-25 → curso 19
INSERT INTO curso_asignatura_docente (curso_id, asignatura_id, docente_id, sala_id) VALUES
(1,  1, 2, 1),  (1,  2, 3, 1),  (1,  3, 4, 1),  (1,  4, 5, 1),  (1,  5, 6, 1),
(2,  1, 2, 2),  (2,  2, 3, 2),  (2,  3, 4, 2),  (2,  4, 5, 2),  (2,  5, 6, 2),
(3,  1, 2, 3),  (3,  2, 3, 3),  (3,  3, 4, 3),  (3,  4, 5, 3),  (3,  5, 6, 3),
(17, 1, 2, 17), (17, 2, 3, 17), (17, 3, 4, 17), (17, 4, 5, 17), (17, 5, 6, 17),
(19, 1, 2, 19), (19, 2, 3, 19), (19, 3, 4, 19), (19, 4, 5, 19), (19, 5, 6, 19);

-- 10. Evaluaciones (2 por CAD = 50 evaluaciones)
-- eval_id 1-2: cad 1 | 3-4: cad 2 | ... | 49-50: cad 25
INSERT INTO evaluaciones (cad_id, nombre, fecha_evaluacion) VALUES
(1,'Prueba 1','2024-04-10'),(1,'Prueba 2','2024-06-14'),
(2,'Prueba 1','2024-04-11'),(2,'Prueba 2','2024-06-15'),
(3,'Prueba 1','2024-04-12'),(3,'Prueba 2','2024-06-16'),
(4,'Prueba 1','2024-04-10'),(4,'Prueba 2','2024-06-17'),
(5,'Prueba 1','2024-04-11'),(5,'Prueba 2','2024-06-18'),
(6,'Prueba 1','2024-04-10'),(6,'Prueba 2','2024-06-14'),
(7,'Prueba 1','2024-04-11'),(7,'Prueba 2','2024-06-15'),
(8,'Prueba 1','2024-04-12'),(8,'Prueba 2','2024-06-16'),
(9,'Prueba 1','2024-04-10'),(9,'Prueba 2','2024-06-17'),
(10,'Prueba 1','2024-04-11'),(10,'Prueba 2','2024-06-18'),
(11,'Prueba 1','2024-04-10'),(11,'Prueba 2','2024-06-14'),
(12,'Prueba 1','2024-04-11'),(12,'Prueba 2','2024-06-15'),
(13,'Prueba 1','2024-04-12'),(13,'Prueba 2','2024-06-16'),
(14,'Prueba 1','2024-04-10'),(14,'Prueba 2','2024-06-17'),
(15,'Prueba 1','2024-04-11'),(15,'Prueba 2','2024-06-18'),
(16,'Prueba 1','2024-04-10'),(16,'Prueba 2','2024-06-14'),
(17,'Prueba 1','2024-04-11'),(17,'Prueba 2','2024-06-15'),
(18,'Prueba 1','2024-04-12'),(18,'Prueba 2','2024-06-16'),
(19,'Prueba 1','2024-04-10'),(19,'Prueba 2','2024-06-17'),
(20,'Prueba 1','2024-04-11'),(20,'Prueba 2','2024-06-18'),
(21,'Prueba 1','2024-04-10'),(21,'Prueba 2','2024-06-14'),
(22,'Prueba 1','2024-04-11'),(22,'Prueba 2','2024-06-15'),
(23,'Prueba 1','2024-04-12'),(23,'Prueba 2','2024-06-16'),
(24,'Prueba 1','2024-04-10'),(24,'Prueba 2','2024-06-17'),
(25,'Prueba 1','2024-04-11'),(25,'Prueba 2','2024-06-18');

-- 11. Notas de Matemática para todos los cursos activos (cad 1,6,11,16,21 → eval par 1-2, 11-12, 21-22, 31-32, 41-42)
INSERT INTO notas (evaluacion_id, estudiante_id, valor) VALUES
-- 1°B-A Matemática
(1,100,5.5),(1,101,4.2),(1,102,6.8),(1,103,5.0),(1,104,6.2),(1,105,4.8),(1,106,7.0),(1,107,5.5),(1,108,4.1),(1,109,6.0),
(2,100,6.0),(2,101,5.1),(2,102,7.0),(2,103,4.5),(2,104,6.5),(2,105,5.3),(2,106,6.8),(2,107,5.8),(2,108,4.6),(2,109,5.5),
-- 1°B-B Matemática
(11,110,5.8),(11,111,4.5),(11,112,6.5),(11,113,5.2),(11,114,6.0),(11,115,4.9),(11,116,6.8),(11,117,5.3),(11,118,4.3),(11,119,6.1),
(12,110,6.1),(12,111,5.0),(12,112,6.8),(12,113,4.8),(12,114,6.3),(12,115,5.4),(12,116,7.0),(12,117,5.7),(12,118,4.8),(12,119,5.9),
-- 2°B-A Matemática
(21,120,5.6),(21,121,4.3),(21,122,6.7),(21,123,5.1),(21,124,6.3),(21,125,4.7),(21,126,7.0),(21,127,5.4),(21,128,4.2),(21,129,6.2),
(22,120,6.2),(22,121,5.2),(22,122,6.9),(22,123,4.6),(22,124,6.6),(22,125,5.5),(22,126,6.7),(22,127,5.9),(22,128,4.7),(22,129,5.6),
-- 1°M-A Matemática
(31,130,5.7),(31,131,4.4),(31,132,6.6),(31,133,5.0),(31,134,6.4),(31,135,4.6),(31,136,6.9),(31,137,5.2),(31,138,4.4),(31,139,6.3),
(32,130,6.3),(32,131,5.3),(32,132,6.8),(32,133,4.7),(32,134,6.7),(32,135,5.6),(32,136,7.0),(32,137,5.8),(32,138,4.9),(32,139,5.7),
-- 2°M-A Matemática
(41,140,5.8),(41,141,4.5),(41,142,6.5),(41,143,5.1),(41,144,6.5),(41,145,4.8),(41,146,6.8),(41,147,5.3),(41,148,4.5),(41,149,6.4),
(42,140,6.4),(42,141,5.4),(42,142,6.7),(42,143,4.8),(42,144,6.8),(42,145,5.7),(42,146,6.9),(42,147,5.9),(42,148,5.0),(42,149,5.8);

-- 12. Asistencia de Matemática para los 5 cursos activos (3 fechas de abril)
INSERT INTO asistencia (estudiante_id, cad_id, fecha, estado, tipo_asistencia) VALUES
-- 1°B-A (cad 1)
(100,1,'2024-04-08','Presente',NULL),(100,1,'2024-04-10','Presente',NULL),(100,1,'2024-04-15','Ausente','Justificada'),
(101,1,'2024-04-08','Presente',NULL),(101,1,'2024-04-10','Tardanza',NULL),(101,1,'2024-04-15','Presente',NULL),
(102,1,'2024-04-08','Presente',NULL),(102,1,'2024-04-10','Presente',NULL),(102,1,'2024-04-15','Presente',NULL),
(103,1,'2024-04-08','Ausente','Injustificada'),(103,1,'2024-04-10','Presente',NULL),(103,1,'2024-04-15','Presente',NULL),
(104,1,'2024-04-08','Presente',NULL),(104,1,'2024-04-10','Presente',NULL),(104,1,'2024-04-15','Presente',NULL),
(105,1,'2024-04-08','Presente',NULL),(105,1,'2024-04-10','Ausente','Justificada'),(105,1,'2024-04-15','Presente',NULL),
(106,1,'2024-04-08','Presente',NULL),(106,1,'2024-04-10','Presente',NULL),(106,1,'2024-04-15','Presente',NULL),
(107,1,'2024-04-08','Tardanza',NULL),(107,1,'2024-04-10','Presente',NULL),(107,1,'2024-04-15','Presente',NULL),
(108,1,'2024-04-08','Presente',NULL),(108,1,'2024-04-10','Presente',NULL),(108,1,'2024-04-15','Ausente','Injustificada'),
(109,1,'2024-04-08','Presente',NULL),(109,1,'2024-04-10','Presente',NULL),(109,1,'2024-04-15','Presente',NULL),
-- 1°B-B (cad 6)
(110,6,'2024-04-08','Presente',NULL),(110,6,'2024-04-10','Presente',NULL),(110,6,'2024-04-15','Presente',NULL),
(111,6,'2024-04-08','Ausente','Justificada'),(111,6,'2024-04-10','Presente',NULL),(111,6,'2024-04-15','Presente',NULL),
(112,6,'2024-04-08','Presente',NULL),(112,6,'2024-04-10','Presente',NULL),(112,6,'2024-04-15','Tardanza',NULL),
(113,6,'2024-04-08','Presente',NULL),(113,6,'2024-04-10','Tardanza',NULL),(113,6,'2024-04-15','Presente',NULL),
(114,6,'2024-04-08','Presente',NULL),(114,6,'2024-04-10','Presente',NULL),(114,6,'2024-04-15','Presente',NULL),
(115,6,'2024-04-08','Presente',NULL),(115,6,'2024-04-10','Ausente','Injustificada'),(115,6,'2024-04-15','Presente',NULL),
(116,6,'2024-04-08','Presente',NULL),(116,6,'2024-04-10','Presente',NULL),(116,6,'2024-04-15','Presente',NULL),
(117,6,'2024-04-08','Tardanza',NULL),(117,6,'2024-04-10','Presente',NULL),(117,6,'2024-04-15','Presente',NULL),
(118,6,'2024-04-08','Presente',NULL),(118,6,'2024-04-10','Presente',NULL),(118,6,'2024-04-15','Ausente','Justificada'),
(119,6,'2024-04-08','Presente',NULL),(119,6,'2024-04-10','Presente',NULL),(119,6,'2024-04-15','Presente',NULL),
-- 2°B-A (cad 11)
(120,11,'2024-04-08','Presente',NULL),(120,11,'2024-04-10','Presente',NULL),(120,11,'2024-04-15','Presente',NULL),
(121,11,'2024-04-08','Presente',NULL),(121,11,'2024-04-10','Ausente','Justificada'),(121,11,'2024-04-15','Presente',NULL),
(122,11,'2024-04-08','Presente',NULL),(122,11,'2024-04-10','Presente',NULL),(122,11,'2024-04-15','Presente',NULL),
(123,11,'2024-04-08','Tardanza',NULL),(123,11,'2024-04-10','Presente',NULL),(123,11,'2024-04-15','Presente',NULL),
(124,11,'2024-04-08','Presente',NULL),(124,11,'2024-04-10','Presente',NULL),(124,11,'2024-04-15','Presente',NULL),
(125,11,'2024-04-08','Ausente','Injustificada'),(125,11,'2024-04-10','Presente',NULL),(125,11,'2024-04-15','Presente',NULL),
(126,11,'2024-04-08','Presente',NULL),(126,11,'2024-04-10','Presente',NULL),(126,11,'2024-04-15','Presente',NULL),
(127,11,'2024-04-08','Presente',NULL),(127,11,'2024-04-10','Tardanza',NULL),(127,11,'2024-04-15','Presente',NULL),
(128,11,'2024-04-08','Presente',NULL),(128,11,'2024-04-10','Presente',NULL),(128,11,'2024-04-15','Ausente','Justificada'),
(129,11,'2024-04-08','Presente',NULL),(129,11,'2024-04-10','Presente',NULL),(129,11,'2024-04-15','Presente',NULL),
-- 1°M-A (cad 16)
(130,16,'2024-04-08','Presente',NULL),(130,16,'2024-04-10','Presente',NULL),(130,16,'2024-04-15','Presente',NULL),
(131,16,'2024-04-08','Presente',NULL),(131,16,'2024-04-10','Presente',NULL),(131,16,'2024-04-15','Ausente','Justificada'),
(132,16,'2024-04-08','Presente',NULL),(132,16,'2024-04-10','Presente',NULL),(132,16,'2024-04-15','Presente',NULL),
(133,16,'2024-04-08','Ausente','Injustificada'),(133,16,'2024-04-10','Presente',NULL),(133,16,'2024-04-15','Presente',NULL),
(134,16,'2024-04-08','Presente',NULL),(134,16,'2024-04-10','Tardanza',NULL),(134,16,'2024-04-15','Presente',NULL),
(135,16,'2024-04-08','Presente',NULL),(135,16,'2024-04-10','Presente',NULL),(135,16,'2024-04-15','Presente',NULL),
(136,16,'2024-04-08','Presente',NULL),(136,16,'2024-04-10','Presente',NULL),(136,16,'2024-04-15','Presente',NULL),
(137,16,'2024-04-08','Tardanza',NULL),(137,16,'2024-04-10','Presente',NULL),(137,16,'2024-04-15','Presente',NULL),
(138,16,'2024-04-08','Presente',NULL),(138,16,'2024-04-10','Ausente','Justificada'),(138,16,'2024-04-15','Presente',NULL),
(139,16,'2024-04-08','Presente',NULL),(139,16,'2024-04-10','Presente',NULL),(139,16,'2024-04-15','Presente',NULL),
-- 2°M-A (cad 21)
(140,21,'2024-04-08','Presente',NULL),(140,21,'2024-04-10','Presente',NULL),(140,21,'2024-04-15','Presente',NULL),
(141,21,'2024-04-08','Presente',NULL),(141,21,'2024-04-10','Presente',NULL),(141,21,'2024-04-15','Tardanza',NULL),
(142,21,'2024-04-08','Presente',NULL),(142,21,'2024-04-10','Presente',NULL),(142,21,'2024-04-15','Presente',NULL),
(143,21,'2024-04-08','Ausente','Injustificada'),(143,21,'2024-04-10','Presente',NULL),(143,21,'2024-04-15','Presente',NULL),
(144,21,'2024-04-08','Presente',NULL),(144,21,'2024-04-10','Presente',NULL),(144,21,'2024-04-15','Presente',NULL),
(145,21,'2024-04-08','Presente',NULL),(145,21,'2024-04-10','Ausente','Justificada'),(145,21,'2024-04-15','Presente',NULL),
(146,21,'2024-04-08','Presente',NULL),(146,21,'2024-04-10','Presente',NULL),(146,21,'2024-04-15','Presente',NULL),
(147,21,'2024-04-08','Tardanza',NULL),(147,21,'2024-04-10','Presente',NULL),(147,21,'2024-04-15','Presente',NULL),
(148,21,'2024-04-08','Presente',NULL),(148,21,'2024-04-10','Presente',NULL),(148,21,'2024-04-15','Ausente','Injustificada'),
(149,21,'2024-04-08','Presente',NULL),(149,21,'2024-04-10','Presente',NULL),(149,21,'2024-04-15','Presente',NULL);

-- 13. Anotaciones
INSERT INTO anotaciones (estudiante_id, docente_id, tipo, descripcion, fecha_registro) VALUES
(103, 2, 'Negativa',  'El alumno no entregó la tarea de Matemáticas por tercera vez consecutiva.',              '2024-04-09 10:30:00'),
(108, 2, 'Negativa',  'Se observa dificultad reiterada para seguir instrucciones en clase.',                     '2024-04-16 09:15:00'),
(101, 3, 'Positiva',  'Excelente participación en la actividad de lectura comprensiva.',                        '2024-04-10 11:00:00'),
(106, 3, 'Positiva',  'Demostró liderazgo y colaboración en el trabajo grupal de Lenguaje.',                    '2024-04-11 11:45:00'),
(133, 2, 'Negativa',  'Alumno interrumpió la clase en reiteradas ocasiones.',                                   '2024-04-08 08:50:00'),
(136, 4, 'Positiva',  'Presentación destacada sobre la Independencia de Chile.',                                '2024-04-12 10:00:00'),
(143, 5, 'Negativa',  'No trajo los materiales requeridos para el laboratorio de Ciencias.',                    '2024-04-10 14:30:00'),
(146, 6, 'Positiva',  'Participó con entusiasmo en la actividad de inglés conversacional.',                     '2024-04-11 15:00:00');

-- 14. Mensajería
INSERT INTO mensajeria (quien_envia, quien_recibe, asunto, cuerpo_mensaje) VALUES
('admin@colegio.cl',       'c.rodriguez@colegio.cl', 'Reunión de coordinación docente',   'Estimada Carla, la reunión de coordinación es el viernes 19 de abril a las 15:00 hrs en la sala de profesores.'),
('admin@colegio.cl',       'm.soto@colegio.cl',       'Reunión de coordinación docente',   'Estimado Marcos, la reunión de coordinación es el viernes 19 de abril a las 15:00 hrs en la sala de profesores.'),
('admin@colegio.cl',       'p.rojas@colegio.cl',      'Reunión de coordinación docente',   'Estimada Patricia, la reunión de coordinación es el viernes 19 de abril a las 15:00 hrs en la sala de profesores.'),
('c.rodriguez@colegio.cl', 'admin@colegio.cl',        'Solicitud de materiales',           'Buen día, necesito solicitar hojas de evaluación y calculadoras para las pruebas de junio. Quedo atenta a su respuesta.'),
('carmen.gonzalez@mail.cl','admin@colegio.cl',         'Consulta sobre asistencia',         'Estimados, quisiera consultar sobre las inasistencias registradas de mi hija Sofía González en el mes de abril.');

-- 15. Sincronizar secuencias con los IDs insertados manualmente
SELECT setval(pg_get_serial_sequence('roles',    'rol_id'),     (SELECT MAX(rol_id)     FROM roles));
SELECT setval(pg_get_serial_sequence('usuarios', 'usuario_id'), (SELECT MAX(usuario_id) FROM usuarios));
SELECT setval(pg_get_serial_sequence('cursos',   'curso_id'),   (SELECT MAX(curso_id)   FROM cursos));
SELECT setval(pg_get_serial_sequence('asignaturas', 'asignatura_id'), (SELECT MAX(asignatura_id) FROM asignaturas));
SELECT setval(pg_get_serial_sequence('curso_asignatura_docente', 'id'), (SELECT MAX(id) FROM curso_asignatura_docente));
SELECT setval(pg_get_serial_sequence('evaluaciones', 'evaluacion_id'), (SELECT MAX(evaluacion_id) FROM evaluaciones));
SELECT setval(pg_get_serial_sequence('notas',    'nota_id'),    (SELECT MAX(nota_id)    FROM notas));
SELECT setval(pg_get_serial_sequence('asistencia', 'asistencia_id'), (SELECT MAX(asistencia_id) FROM asistencia));
SELECT setval(pg_get_serial_sequence('anotaciones', 'anotacion_id'), (SELECT MAX(anotacion_id) FROM anotaciones));
SELECT setval(pg_get_serial_sequence('mensajeria', 'id'), (SELECT MAX(id) FROM mensajeria));
SELECT setval(pg_get_serial_sequence('salas', 'sala_id'), (SELECT MAX(sala_id) FROM salas));

